# Generated by Django 5.0.1 on 2024-02-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(to='core.speaker'),
        ),
    ]
